### PR TITLE
Updates list of known feature tags

### PR DESCRIPTION
**Pull request by khaledhosny**
Fixes several “The FeatureRecord tag is valid, but unregistered” warnings. Based on:
 > http://www.microsoft.com/typography/otspec/featurelist.htm

### CODE REVIEW

**Comment by HinTak** [comment]
If the feature list is different between different version of the spec (and presumably different versions of some table) - you will also need to check the version of the table.

I feel that you might be a bit keen on making Font Validator quieter, but on the whole, it should err on the strict side and warn the user about anything and let him/her decide whether his/her font should be changed or not.

**Comment by HinTak** [comment]
Okay, neither the GSUB and the GPOS table had ever changed version.

**Comment by khaledhosny** [comment]
Indeed, so it makes no sense to warn about perfectly valid *and* registered feature tags.

**Comment by HinTak** [comment]
My reservation about this pull in fact was the one we did not discuss: I am not prepared to take on cosmetic changes which serves no functional purpose, at this stage. i.e. I won't take re-indentations "because it is not in style X (i.e. "it hurts my eyes")". After thinking about it for a day, I think I am going to do it in a different way, from how you did it.

I'll add your repo to my list of remotes to cherry-pick from; and thanks for the report.

**Comment by HinTak** [comment]
I have sync the feature list to the 2015 spec; and also add back the 4 tags which are removed. They should trigger a warning with an appropriate message if used (TODO). You are welcomed to contribute to warn for the 4 withdrawn tags.

**Pull request closed without merging**
